backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

media_library:
  name: cloudinary
  config:
    cloud_name: dropoutfm
    api_key: 748393431139731

# media_library:
#   name: uploadcare
#   config:
#     publicKey: 49c9c8a983d0033fb5fe

collections:
  - name: "track"
    label: "Track"
    folder: "src/pages/tracks"
    create: true
    slug: "{{artist}}-{{title}}"
    summary: "{{artist}}: {{title}} ({{year}})"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "track-page"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Album", name: "album", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Publish Date", name: "datetime", widget: "datetime", required: false, timeFormat: false}
  - name: "mix"
    label: "Mix"
    folder: "src/pages/mixes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mix-page"}
      - {label: "Image", name: "image", widget: "file"}
      - {label: "Week", name: "week", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tracks", name: "tracks", widget: "relation", collection: "tracks", searchFields: ["title", "artist"]}
