backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

media_library:
  name: cloudinary
  config:
    cloud_name: dropoutfm
    api_key: 748393431139731

# media_library:
#   name: uploadcare
#   config:
#     publicKey: 49c9c8a983d0033fb5fe

collections:
  - name: "track"
    label: "Track"
    folder: "src/pages/tracks"
    create: true
    slug: "{{artist}}-{{title}}"
    summary: "{{artist}}: {{title}}"
    fields:
      - {name: templateKey, widget: hidden, default: track-page}
      - {name: artist, widget: string}
      - {name: album, widget: string}
      - {name: title, widget: string}
      - {name: year, widget: string}
      - {name: cover, widget: image, required: false}
      - {name: file, widget: file, required: false}
      - {label: "Publish Date", name: datetime, widget: datetime, required: false, timeFormat: false, default: ""}
  - name: "mix"
    label: "Mix"
    folder: "src/pages/mixes"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: templateKey, widget: hidden, default: mix-page}
      - {name: image, widget: file}
      - {name: week, widget: datetime}
      - {name: title, widget: string}
      - {name: tracks, widget: relation, collection: tracks, searchFields: [title, artist]}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index"
        name: "index"
        file: "src/pages/index.md"
        fields:
          - {name: title, widget: string}
          - {name: subtitle, widget: string}
          - {name: newsletter, widget: boolean, label: "Display Newsletter"}
