backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "track"
    label: "Track"
    folder: "src/pages/tracks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "track-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: "now"}
  - name: "mix"
    label: "Mix"
    folder: "src/pages/mixes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mix-page"}
      - {label: "Image", name: "image", widget: "file"}
      - {label: "Week", name: "week", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tracks", name: "tracks", widget: "relation", collection: "tracks", searchFields: ["title", "artist"]}
